
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/du2/22CS30065/SE-ORNet/train.py", line 4, in <module>
    import pytorch_lightning as pl
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/utilities/apply_func.py", line 38, in <module>
    _CPU_DEVICES = ("cpu", torch.device("cpu"))
/home/du2/22CS30065/miniconda3/envs/se_ornet2/lib/python3.10/site-packages/pytorch_lightning/utilities/apply_func.py:38: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484808560/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _CPU_DEVICES = ("cpu", torch.device("cpu"))
Traceback (most recent call last):
  File "/home/du2/22CS30065/SE-ORNet/train.py", line 9, in <module>
    from utils import switch_functions
  File "/home/du2/22CS30065/SE-ORNet/utils/switch_functions.py", line 3, in <module>
    from data.point_cloud_db.tosca import TOSCA
  File "/home/du2/22CS30065/SE-ORNet/data/point_cloud_db/tosca.py", line 5, in <module>
    from data.point_cloud_db.shrec import apply_download
  File "/home/du2/22CS30065/SE-ORNet/data/point_cloud_db/shrec.py", line 8, in <module>
    from visualization.mesh_container import MeshContainer
  File "/home/du2/22CS30065/SE-ORNet/visualization/mesh_container.py", line 5, in <module>
    from plyfile import PlyData
ModuleNotFoundError: No module named 'plyfile'
